apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: hw-event-proxy-service-monitor
  name: hw-event-proxy-service-monitor
  namespace: {{ .Namespace }}
spec:
  jobLabel: cloud-native-events
  endpoints:
    - interval: 30s
      port: metrics
      bearerTokenFile: "/var/run/secrets/kubernetes.io/serviceaccount/token"
      scheme: "https"
      tlsConfig:
        caFile: "/etc/prometheus/configmaps/serving-certs-ca-bundle/service-ca.crt"
        serverName: "hw-event-proxy-service.cloud-native-events.svc"
  selector:
    matchLabels:
      app: hw-event-proxy-service
  namespaceSelector:
    matchNames:
      - {{ .Namespace }}
